version: '3'
services:
    php-apache:
        build:
          context: "."
        ports:
            - 8080:80
        volumes:
            - ./DocumentRoot:/var/www/html
        links:
            - 'mariadb'
    mariadb:
        image: mariadb:10.1
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            TZ: "Europe/Brussels"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: "wordpress"
            MYSQL_PASSWORD: "password"
            MYSQL_DATABASE: "wordpress"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - mariadb
        ports:
            - 9000:80
        environment:
            MYSQL_USERNAME: "root"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            PMA_HOST: mariadb
volumes:
    mariadb:
